name: Test

on:
  - push
  - pull_request

jobs:
  test-in-matrix:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        ipfs:
          - 0.4
          - 0.5
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} IPFS-${{ matrix.ipfs }}
    steps:
      - uses: actions/checkout@master
      - name: Set up and Run IPFS ${{ matrix.ipfs }}
        id: ipfs_setup
        uses: ./
        with:
          ipfs_version: ${{ matrix.ipfs }}
          run_daemon: true
      - name: Test IPFS ${{ steps.ipfs_setup.outputs.resolved_ipfs_version }} CLI
        shell: bash
        run: ipfs cat ${{ steps.ipfs_setup.outputs.welcome_ref }}/readme
      - name: Test IPFS ${{ steps.ipfs_setup.outputs.resolved_ipfs_version }} API
        shell: bash
        run: |
          set -o pipefail
          curl -sX POST http://localhost:5001/api/v0/version | jq -e
          curl -sX POST http://localhost:5001/api/v0/version | jq -e '(.Version=="${{ steps.ipfs_setup.outputs.resolved_ipfs_version }}")'
